/* ============================================
VMX-pi HAL source code is placed under the MIT license
Copyright (c) 2017 Kauai Labs
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
===============================================
*/

#include "AHRSProtocol.h"

/**
 * The ITimestampedDataSubscriber interface provides a method for consumers
 * of navX-Model device data to be rapidly notified whenever new data
 * has arrived.
 *
 * - timestampedDataReceived():  reception of sensor-timestamped data
 *
 *  A "sensor" timestamp is provided, generated by the navX-Model device, which is
 *  at millisecond resolution.  A "system timestamp", also at millisecond resolution,
 *  is also provided, which represents as accurately as possible the time at which the 
 *  data was acquired from the navX-Model device.  Note that the "system timestamp" 
 *  typically has more jitter since it is generated by the host of the navX-Model 
 *  device.
 *
 *  Thus, in general sensor timestamps are preferred, as they are generated
 *  by the navX-Model device motion processor and has a greater accuracy (+/- 1ms) than the
 *  system timestamp which is vulnerable to latencies introduced by the
 *  host operating system.
 *
 *  The system timestamp is provided to allow performance monitoring of the 
 *  navX-Model device host's data acquisition process.
**/
class ITimestampedDataSubscriber {
public:
	virtual ~ITimestampedDataSubscriber(){}
    virtual void timestampedDataReceived( long system_timestamp, long sensor_timestamp, AHRSProtocol::AHRSUpdateBase& sensor_data, void * context ) = 0;
};
